### ISSUE TITLE
Example of box with provisionning

### ISSUE THREAD

**Issue by vsidou** [sagiadinos/garlic-launcher#1]
Hi,

Thanks for your piece of software.
It works great on a tablet and as you wrote won't work on Android TV :(
Are there any recommanded box on which you tested that i could try please ?

Thanks
Siddique

**Comment by sagiadinos** [comment]
Hello Siddique,

My preferred development setup is a 14'' Android 7.1 Tablet with a Rockchip SoC's rk3399 and two further customer boxes with similar SoCs.  
The garlic-launcher is also tested by my business partner with their Android boxes before using in projects.
The devices mostly were created by Asian manufacturers with rooted Android 7 - 9  images.

The good news. There are no compatibility issues so far. 
The bad news. The devices are branded, configured explicitly by the customers and have names like cube2, Android TV Box, AiO or k10plus.

My company partner tried successfully a cheap circled T95Q Amlogic S905X3 device some moths ago with Android 8.1.  
https://www.ebay.fr/itm/254789727774?var=554603548987
https://www.banggood.com/de/Sunvell-T95Q-Amlogic-S905X3-4GB-RAM-64GB-ROM-Android-9_0-5G-WIFI-1000M-LAN-bluetooth-4_1-4K-TV-Box-p-1385214.html

Now they seem to have Android 9. 
Problem with this cheap TV boxes: If you order two in different time intervals, you cannot even be sure that you get the same device/board. 

What I can definitely advise you not to use, are HDMI sticks. They will work at first, but you will get power and overheating problems after a while. Especially with 4k content.

Email me on ns@smil-control.com if you like. I can give you a contact with my hardware partner. He has more experiences in this field than me.

kind regards 
Niko
