### ISSUE TITLE
How to update the player via launcher

### ISSUE THREAD

**Issue by jf133** [sagiadinos/garlic-launcher#2]
Hi Niko -- you describe in notes that you can upgrade the garlic-player to the "latest" version via the launcher. Can you please describe how that works? 

Thank you!

**Comment by sagiadinos** [comment]
That is real timing. I just released a new garlic-player website with documentation.

You find the description here: [Software/Firmware-Updates](https://garlic-player.com/garlic-player/docs/essentials/maintenance-tasks/#firmware_update)
