### ISSUE TITLE
I found a solution for garlic launcher to work for android 11

### ISSUE THREAD

**Issue by leonardomrl** [sagiadinos/garlic-launcher#3]
First, congratulations on the project, really very good. I was facing a problem precisely with the garlic launcher in the android 11+ version, the message appeared that I could not put the garlic launcher as the device's owner.

The solution I found by adding the admin permission xml.

Copy android.software.device_admin.xml from [here](https://android.googlesource.com/platform/frameworks/native/+/android-7.1.1_r58/data/etc/android.software.device_admin.xml).

Send ADB Command which is written below.
`adb remount`

Send ADB Command which is written below.
`adb push android.software.device_admin.xml /system/etc/permissions/android.software.device_admin.xml`

Send ADB Command which is written below.
`adb shell sync`

Reboot.

Due to the tv box equipment changing a lot of version, I was in this battle to get it, hope it helps.

**Comment by sagiadinos** [comment]
Hello leobardomrl, 

Great, thank you very much for sharing your experience.

May I ask you were you tested it? Rooted or unrooted Android?

Kind regards
Niko

**Comment by leonardomrl** [comment]
@sagiadinos In the players I'm using I have root access, I haven't tested whether to copy this permission you need this level of privilege, but it was the only way I managed to make it work. 

We have many players with android 4.4.2 , I'm testing with garlic player version 0.3, do you think I can compile the current version (launcher and garlic) just by changing the minimum required android version?

**Comment by sagiadinos** [comment]
Normally, the launcher recognizes rooted devices and sets himself to device owner mode after first launch, but as there is no secure root detection possible, this procedure sometimes fails and needs to proceed manually.

As most of my test devices are also rooted, I use the virtual devices from Android Studio.
With a virtual Android 11, the [adb command](https://garlic-player.com/garlic-launcher/docs/installation/#device_owner) :

`adb shell dpm set-device-owner com.sagiadinos.garlic.launcher/.receiver.AdminReceiver
`
did the job. Did you try this command and it failed?

### Compile Android 4.4.2. 
If you take Qt 5.12.12 AFAIK it should be possible to compile garlic-player with Android SDK 19. Launcher for 4.4.2.
I tried it only once with an 4.4.2. device some years ago, but we get video stuttering assuming the hw acceleration not work correctly via Qt's Android multimedia wrapper.

And you will not be able to use the launcher as some device owner functions like reboot supported only from SDK 24. Another example: for setLockTaskPackages SDK 21 is needed etc.
